name: Process Historical Weather Data

on:
  workflow_dispatch:
    inputs:
      days_back:
        description: 'Number of days back to process (default: 7)'
        required: false
        default: '7'

permissions:
  contents: write

jobs:
  process-historical-weather-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin python3-gdal curl jq wget
          gdalinfo --version

      - name: Process Historical Weather Data
        run: |
          #!/bin/bash
          set -euo pipefail

          DAYS_BACK="${{ github.event.inputs.days_back }}"
          echo "Processing weather data for the past $DAYS_BACK days..."

          mkdir -p raw-data processed-data

          for ((i=0; i<${DAYS_BACK}; i++)); do
            gfs_date=$(date -u -d "$i day ago" +%Y%m%d)
            for gfs_run in 00 06 12 18; do
              echo "Processing $gfs_date $gfs_run Z run..."

              # Wind U
              wget -q "https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file=gfs.t${gfs_run}z.pgrb2.0p25.f000&lev_10_m_above_ground=on&var_UGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.${gfs_date}%2F${gfs_run}%2Fatmos" \
                -O "raw-data/wind_u_${gfs_date}_${gfs_run}z.grib" || true

              # Wind V
              wget -q "https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file=gfs.t${gfs_run}z.pgrb2.0p25.f000&lev_10_m_above_ground=on&var_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.${gfs_date}%2F${gfs_run}%2Fatmos" \
                -O "raw-data/wind_v_${gfs_date}_${gfs_run}z.grib" || true

              # Cloud Cover
              wget -q "https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file=gfs.t${gfs_run}z.pgrb2.0p25.f000&lev_entire_atmosphere=on&var_TCDC=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.${gfs_date}%2F${gfs_run}%2Fatmos" \
                -O "raw-data/cloud_${gfs_date}_${gfs_run}z.grib" || true

              # Temperature (2m)
              wget -q "https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file=gfs.t${gfs_run}z.pgrb2.0p25.f000&lev_2_m_above_ground=on&var_TMP=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.${gfs_date}%2F${gfs_run}%2Fatmos" \
                -O "raw-data/temp_${gfs_date}_${gfs_run}z.grib" || true

              # Reflectivity
              wget -q "https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file=gfs.t${gfs_run}z.pgrb2.0p25.f000&lev_entire_atmosphere=on&var_REFC=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.${gfs_date}%2F${gfs_run}%2Fatmos" \
                -O "raw-data/reflectivity_${gfs_date}_${gfs_run}z.grib" || true

              # Process data
              cd raw-data
              if [[ -f "wind_u_${gfs_date}_${gfs_run}z.grib" && -f "wind_v_${gfs_date}_${gfs_run}z.grib" ]]; then
                gdalbuildvrt -separate "wind_${gfs_date}_${gfs_run}z.vrt" "wind_u_${gfs_date}_${gfs_run}z.grib" "wind_v_${gfs_date}_${gfs_run}z.grib" "wind_v_${gfs_date}_${gfs_run}z.grib"
                gdal_translate -ot Byte -scale -30 30 0 255 -of PNG "wind_${gfs_date}_${gfs_run}z.vrt" "../processed-data/wind_${gfs_date}_${gfs_run}z.png"
              fi

              if [[ -f "cloud_${gfs_date}_${gfs_run}z.grib" ]]; then
                gdal_translate -ot Byte -scale 0 100 0 255 -of PNG "cloud_${gfs_date}_${gfs_run}z.grib" "../processed-data/cloud_${gfs_date}_${gfs_run}z.png"
              fi

              if [[ -f "temp_${gfs_date}_${gfs_run}z.grib" ]]; then
                gdal_translate -ot Byte -scale 213.15 325.15 0 255 -of PNG "temp_${gfs_date}_${gfs_run}z.grib" "../processed-data/temp_${gfs_date}_${gfs_run}z.png"
              fi

              if [[ -f "reflectivity_${gfs_date}_${gfs_run}z.grib" ]]; then
                gdal_translate -ot Byte -scale 0 70 0 255 -of PNG "reflectivity_${gfs_date}_${gfs_run}z.grib" "../processed-data/reflectivity_${gfs_date}_${gfs_run}z.png"
              fi

              # Back to repo root
              cd ..
            done
          done

      - name: Commit and push processed data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add processed-data/
          if [ -n "$(git diff --staged)" ]; then
            git commit -m "Add historical weather data for past ${{ github.event.inputs.days_back }} days"
            git push
          else
            echo "No new data to commit"
          fi
